POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "teste",
  "url": "http://rocketseat.com.br"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/api/metrics

###

GET http://localhost:3333/rocketseat
